The front-end for a user to enter upload verification code given to them (Addressing issue #31)
JoshuaBuditama/slowvid pull request #71
Opened 2020-10-09 06:06 UTC by JoshuaBuditama

This PR contains a simple front end for the upload page, where a user can enter token given to them.
The format of the token addressed in this UI is all uppercase alphabets and with maximum length of 4.
The format of the token can be changed later if required.

2020-10-09 20:48 UTC, cskeogh requested changes
Nice work. I like the use of the stylesheet.

2020-10-09 20:48 UTC, cskeogh commented on front-end/src/components/UploadForm.tsx
> +                      disabled={(!verificationToken.match(/^[A-Z]+$/) || verificationToken.length !== 4)}
`verificationToken.match(/^[A-Z]+$/)` code is repeated three times in this file. Place in a function to help maintainability (the verification code may have to change depending on the server).

2020-10-09 20:48 UTC, cskeogh commented on front-end/src/components/UploadForm.tsx
> +            Please enter the healthcare code provided to you by the healthcare professional
[master L12](https://github.com/JoshuaBuditama/slowvid/blob/master/front-end/src/components/Notifications.tsx#L12) uses the term 'health care' (note space)

2020-10-09 20:48 UTC, cskeogh commented on front-end/src/components/UploadForm.tsx
> +          <h1 className="title">Sharing my close contacts with healthcare professional</h1>
[master L12](https://github.com/JoshuaBuditama/slowvid/blob/master/front-end/src/components/Notifications.tsx#L12) uses the term 'health care' (note space)

2020-10-10 03:02 UTC, JoshuaBuditama commented on front-end/src/components/UploadForm.tsx
> +  }
@cskeogh I have addressed the maintainability issue by creating a new function that checks the validity of the token.

2020-10-10 03:04 UTC, JoshuaBuditama commented on front-end/src/components/UploadForm.tsx
> +    if(verificationToken.match(validTokenCombination) && verificationToken.length === validTokenLength)
@cskeogh I have addressed the maintainability issue by creating a new function that checks the validity of the token and call it whenever I need to check the validity of the token in the HTML element

2020-10-10 03:07 UTC, JoshuaBuditama commented
@cskeogh Thanks for the review!
I have fixed the maintainability issue and have changed 'healthcare' to 'health care' to better reflect what's on the  master branch.
Please let me know if there is any other issue!

2020-10-10 06:10 UTC, cskeogh approved these changes
Looks good. Good to merge

2020-10-10 06:42 UTC, merged